ARDMK_DIR = /usr/share/arduino
BOARD_TAG = uno
ARDUINO_PORT = /dev/ttyACM0

include $(ARDMK_DIR)/Arduino.mk



ARDUINO_DIR= /usr/share/arduino
BOARD_TAG = uno
TARGET= main
MCU= atmega328p
F_CPU= 16000000
ARDUINO_PORT = /dev/ttyACM0
AVRDUDE_ARD_BAUDRATE= 115200
AVRDUDE_ARD_PROGRAMMER = arduino
 
include $(ARDMK_DIR)/Arduino.mk
