obj-m = module_test.o

default :
	make ARCH=arm CROSS_COMPILE=/opt/toolchains/linux-x86/aarch64/aarch64-linux-android-4.8/bin/aarch64-linux-android- -C /home/ji-hun-kim/link/joon_kernel SUBDIRS=/home/ji-hun-kim/link/ldd3/lsi_example modules 
clean :
	make ARCH=arm CROSS_COMPILE=/opt/toolchains/linux-x86/aarch64/aarch64-linux-android-4.8/bin/aarch64-linux-android- -C /home/ji-hun-kim/link/joon_kernel SUBDIRS=/home/ji-hun-kim/link/ldd3/lsi_example clean
