#ARDUINO_DIR   = /Applications/Arduino.app/Contents/Resources/Java #This is not working.. reference from sudar

#ARDMK_DIR = /usr/share/arduino
ARDMK_DIR = /usr/local/opt/arduino-mk
BOARD_TAG = uno
#ARDUINO_PORT = /dev/ttyACM0
PORT_NAME = /dev/tty.usbmodem1421
AVRDUDE	  = /usr/local/bin/avrdude

include $(ARDMK_DIR)/Arduino.mk
